### ISSUE TITLE
Can not cd in a new created folder !

### ISSUE THREAD

**Issue by CozmoCyke** [LIKO-12/LIKO-12#205]
**Describe the bug**

**To Reproduce**
1. > mkdir png
2. PNG folder create success
3. > cd png
4. Crash !

**Expected behavior**
execute command cd and choose folder

**Screenshot

[==[ Engine Error ]==]

 - Please report this to the developer !
   Github: http://bit.ly/liko12

Engine/coreg.lua:34: /Drives/C/terminal.lua:549: Folder doesn't exists !

Traceback:
----------

Engine/errhand.lua:52: in function 'handler'
[C]: in function 'error'
Engine/coreg.lua:34: in function 'resumeCoroutine'
/Peripherals/CPU.lua:15: in function 'triggerEvent'
/Peripherals/Keyboard.lua:23: in function </Peripherals/Keyboard.lua:22>
Engine/events.lua:52: in function 'trigger'
main.lua:84: in function <main.lua:67>
[C]: in function 'xpcall'

**Smartphone (please complete the following information):**
 - Device: Moto g5
 - OS:  Android7.0

**Comment by TheSainEyereg** [comment]
I have this problem too.

1. mkdir downloads

2. cd downloads

[==[ Engine Error ]==]

 - Please report this to the developer !
   Github: http://bit.ly/liko12

Engine/coreg.lua:34: /Drives/C/terminal.lua:549: Folder doesn't exists !


Traceback:
----------

Engine/errhand.lua:52: in function 'handler'
[C]: in function 'error'
Engine/coreg.lua:34: in function 'resumeCoroutine'
/Peripherals/CPU.lua:15: in function 'triggerEvent'
/Peripherals/Keyboard.lua:23: in function </Peripherals/Keyboard.lua:22>
Engine/events.lua:52: in function 'trigger'
main.lua:84: in function <main.lua:67>
[C]: in function 'xpcall'

- windows 10 1803

**Comment by Rami-Sabbagh** [comment]
@Positive07 and @boredom101 Please inspect this:
- Check the HDD peripheral
- Check the terminal path resolved
- The `resolve` command might help

**Comment by boredom101** [comment]
This is fixed in pending pull request #209 .

**Comment by pablomayobre** [comment]
I'm reopening this issue based on @Cheezed [report](https://github.com/LIKO-12/LIKO-12/pull/209#issuecomment-425613936)

> ![ezgif com-optimize](https://user-images.githubusercontent.com/37090700/46240831-5714ea80-c362-11e8-96c2-998400b25f65.gif)

The PR is an improvement but the actual issue is not fixed

**Comment by ghost** [comment]
@Positive07 It works now.
