### ISSUE TITLE
Mac Accessibility Shortcuts

### ISSUE THREAD

**Issue by ghost** [LIKO-12/LIKO-12#210]
**Is your feature request related to a problem? Please describe.**
Not exactly. I've just realized that using the command (⌘) and the Backspace key on Mac keyboards don't trigger the normal CTRL and Delete key.

**Describe the solution you'd like**
I like to be able to press the Backspace (delete) key on the BIOS setup in order to configure it, and the command key to copy and paste.

**Describe alternatives you've considered**
On Macs, the delete key is basically also the backspace key on a normal keyboard. Maybe having something like Alt+Backspace could trigger the normal Delete key.

**Additional context**
Again, the delete key on Mac keyboard is used as the Backspace key, and there is no actual Delete key for these kinds of keyboards.
![Keyboard](https://user-images.githubusercontent.com/37090700/46247874-92490500-c3c6-11e8-9b9a-d78923d13a6a.jpg)

**Comment by ghost** [comment]
Going to *hopefully* be solved in #211.

**Comment by pablomayobre** [comment]
The 7abb4255de85d359e90bef77ed0a9af93902c84d commit, partially fixes this issue, by aliasing Cmd key with the Ctrl key (only on OSX).

Backspace -> Delete alias is still pending

**Comment by boredom101** [comment]
I think this was fixed in #212

**Comment by pablomayobre** [comment]
No, this wasn't fixed entirely, the issue requests two changes:

- [x] Alias Command key to Ctrl key
- [ ] Alias Alt+Backspace to Delete key

**Comment by Rami-Sabbagh** [comment]
`Alt+Backspace` could be implemented the same way, just check for `love.keyboard.isDown("lalt","ralt")`

**Comment by Rami-Sabbagh** [comment]
Fixed in #256
